"""add sim order fill_kind

Revision ID: 3597922e5e09
Revises: a6c1e58d734b
Create Date: 2026-07-16 14:10:59.941226

"""
from alembic import op
import sqlalchemy as sa


revision = '3597922e5e09'
down_revision = 'a6c1e58d734b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sim_orders', sa.Column('fill_kind', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sim_orders', 'fill_kind')
    # ### end Alembic commands ###
