"""initial schema

Revision ID: 97f4da530b0e
Revises: 
Create Date: 2026-07-08 12:10:22.348390

"""
from alembic import op
import sqlalchemy as sa


revision = '97f4da530b0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_log_created_at'), 'ai_usage_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_log_model'), 'ai_usage_log', ['model'], unique=False)
    op.create_table('sim_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'symbol', name='uq_stocks_market_symbol')
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=False)
    op.create_table('ai_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', 'kind', name='uq_ai_reports_daily')
    )
    op.create_index(op.f('ix_ai_reports_stock_id'), 'ai_reports', ['stock_id'], unique=False)
    op.create_index(op.f('ix_ai_reports_trade_date'), 'ai_reports', ['trade_date'], unique=False)
    op.create_table('daily_prices',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('stock_id', 'date')
    )
    op.create_table('etf_nav',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('premium_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('stock_id', 'date')
    )
    op.create_table('indicators',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ma5', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('ma20', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('ma60', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kd_k', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kd_d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('stock_id', 'date')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('predicted_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_stock_id'), 'predictions', ['stock_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('ai_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', name='uq_watchlist_stock')
    )
    op.create_table('sim_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('decided_by', sa.String(length=4), nullable=False),
    sa.Column('ai_report_id', sa.Integer(), nullable=True),
    sa.Column('reject_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['sim_accounts.id'], ),
    sa.ForeignKeyConstraint(['ai_report_id'], ['ai_reports.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_orders_account_id'), 'sim_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_sim_orders_stock_id'), 'sim_orders', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_orders_stock_id'), table_name='sim_orders')
    op.drop_index(op.f('ix_sim_orders_account_id'), table_name='sim_orders')
    op.drop_table('sim_orders')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_predictions_stock_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('indicators')
    op.drop_table('etf_nav')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_ai_reports_trade_date'), table_name='ai_reports')
    op.drop_index(op.f('ix_ai_reports_stock_id'), table_name='ai_reports')
    op.drop_table('ai_reports')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('sim_accounts')
    op.drop_index(op.f('ix_ai_usage_log_model'), table_name='ai_usage_log')
    op.drop_index(op.f('ix_ai_usage_log_created_at'), table_name='ai_usage_log')
    op.drop_table('ai_usage_log')
    # ### end Alembic commands ###
