"""watch groups and ai overviews

Revision ID: af0e53ed521e
Revises: 9d06114a8767
Create Date: 2026-07-09 12:01:36.088983

"""
from alembic import op
import sqlalchemy as sa


revision = 'af0e53ed521e'
down_revision = '9d06114a8767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_overviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'trade_date', name='uq_overview_daily')
    )
    op.create_table('watch_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'name', name='uq_group_market_name')
    )
    # SQLite 不支援 ALTER ADD CONSTRAINT，用 batch 模式重建表
    with op.batch_alter_table('watchlists') as batch:
        batch.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
        batch.create_foreign_key('fk_watchlists_group', 'watch_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists') as batch:
        batch.drop_constraint('fk_watchlists_group', type_='foreignkey')
        batch.drop_column('sort_order')
        batch.drop_column('group_id')
    op.drop_table('watch_groups')
    op.drop_table('ai_overviews')
    # ### end Alembic commands ###
